test:
  image: docker:20.10.21
  services:
    - name: docker:20.10.21-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker images
    - docker run hello-world
    - docker-compose -f dc_test.yml up