version: "3.6"
services:

  s1:
    build:
      dockerfile: Dockerfile1
    volumes:
      - vol1:/volume
    command:
      - ls /volume

  s2:
    image: alpine
    volumes:
      - vol1:/my_volume
    command:
      - ls /

volumes:
  vol1: